DEFAULT_START_DATE <- "2019-12-01"
DEFAULT_APOCALYPSE_DATE <- "2020-02-18"
DEFAULT_END_DATE <- "2099-12-31"
DEFAULT_STOCK_TYPE <- "Common stock" # Stock types: "Common stock", "ETF", "ETC", "ETN", "Other"
DEFAULT_NUMBER_OF_STOCKS <- 20
DEFAULT_WINDOW_SIZE <- 15
DEFAULT_NUMBER_OF_CHARACTERS <- 11
DEFAULT_OUTPUT_DIRECTORY <- "plots"
DEFAULT_UNTIL_MOST_RECENT_DAY <- FALSE
DEFAULT_NO_LOSS_UNTIL_APOCALYPSE_DATE <- TRUE
DEFAULT_NUMBER_OF_MOST_TRADED_STOCKS <- NULL
DEFAULT_NUMBER_OF_MOST_VOLUME_STOCKS <- NULL
